[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/schedule"
  to = "/.netlify/functions/schedule"
  status = 200

[[redirects]]
  from = "/api/logo"
  to = "/.netlify/functions/logo"
  status = 200
