const NAV='https://api-gw.sports.naver.com/schedule/games';
const L='https://lolesports.com/ko-KR/leagues/lck,lpl,worlds';
const V='https://www.vlr.gg/team/11060/nongshim-redforce';
const memory=new Map();const pendingSchedules=new Map();
async function parallelMap(items,limit,fn){let cursor=0;const out=new Array(items.length);await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const i=cursor++;out[i]=await fn(items[i],i);}}));return out;}

export function safeLogo(value){try{const url=new URL(String(value||'').replace(/^http:/,'https:'),'https://www.vlr.gg');return url.protocol==='https:'&&['sports-phinf.pstatic.net','static.lolesports.com','owcdn.net'].includes(url.hostname)?url.href:null;}catch{return null;}}
function lolParticipants(teams){return teams.map(t=>({name:t.code||t.name,logo:safeLogo(t.image)}));}

export const textOnly=s=>s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&(?:nbsp|sdot);/g,' ').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(18000),headers:{'Accept':'text/html,application/json'}});if(!r.ok)throw Error(`출처 응답 ${r.status}`);return r.text();}
export function kst(iso){const d=new Date(iso);if(!Number.isFinite(d.getTime()))throw Error('경기 시간 형식 변경');const s=new Date(d.getTime()+9*3600000).toISOString();return {date:s.slice(0,10),time:s.slice(11,16)};}
function event(team,id,iso,title,venue,source,status='예정'){return {team,id,...kst(iso),title,venue,source,status};}
export function parseNaver(raw,team){const j=JSON.parse(raw);if(!j.success||!Array.isArray(j.result?.games))throw Error('네이버 일정 형식 변경');const match={lotte:g=>g.homeTeamCode==='LT'||g.awayTeamCode==='LT',daegu:g=>g.homeTeamName==='대구'||g.awayTeamName==='대구',barca:g=>g.homeTeamName==='바르셀로나'||g.awayTeamName==='바르셀로나'}[team];return j.result.games.filter(match).map(g=>{const status=g.cancel?'취소':g.suspended||g.postponed?'연기':g.statusCode==='RESULT'?'종료':g.statusCode==='BEFORE'?'예정':'진행 중';const e=event(team,`nav-${g.gameId}`,g.gameDateTime.match(/(?:Z|[+-]\d\d:\d\d)$/)?g.gameDateTime:g.gameDateTime+'+09:00',`${g.homeTeamName} vs ${g.awayTeamName}`,`${g.categoryName} · ${g.stadium||'장소 미정'}`,`https://m.sports.naver.com/game/${encodeURIComponent(g.gameId)}`,status);e.participants=[{name:g.homeTeamName,logo:safeLogo(g.homeTeamEmblemUrl)},{name:g.awayTeamName,logo:safeLogo(g.awayTeamEmblemUrl)}];if(g.timeTbd)e.time=null;if(status==='종료')e.score=`${g.homeTeamScore} : ${g.awayTeamScore}`;return e;});}
async function naver(team,month){const upper={lotte:'kbaseball',daegu:'kfootball',barca:'wfootball'}[team];const [y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate();const starts=Array.from({length:Math.ceil(last/7)},(_,i)=>1+i*7);const chunks=await parallelMap(starts,5,async start=>{const end=Math.min(start+6,last);const q=new URLSearchParams({fields:'basic,schedule,postponed',upperCategoryId:upper,fromDate:month+'-'+String(start).padStart(2,'0'),toDate:month+'-'+String(end).padStart(2,'0'),size:'500'});const raw=await get(NAV+'?'+q);if(JSON.parse(raw).result?.games?.length>=500)throw Error('네이버 조회 범위 초과');return parseNaver(raw,team);});return {events:[...new Map(chunks.flat().map(e=>[e.id,e])).values()],scope:'선택한 달 · 네이버 스포츠'};}
// Parse only a JSON array; never evaluate upstream scripts.
export function arraysForKey(html,key){const out=[];let cursor=0;const token=`"${key}":`;while((cursor=html.indexOf(token,cursor))!==-1){let start=cursor+token.length;while(/\s/.test(html[start]))start++;cursor=start+1;if(html[start]!=='[')continue;let depth=0,str=false,escaped=false;for(let i=start;i<html.length;i++){let c=html[i];if(str){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')str=false;}else if(c==='"')str=true;else if(c==='['||c==='{')depth++;else if(c===']'||c==='}'){if(--depth===0){try{out.push(JSON.parse(html.slice(start,i+1)));}catch{}cursor=i+1;break;}}}}return out;}
const LOL_FIRST_TEAM_IDS={HLE:'100205573496804586',BLG:'99566404853854212'};
export function isFirstTeamLol(t){const id=LOL_FIRST_TEAM_IDS[t?.code];return !!id&&typeof t.id==='string'&&(t.id===id||t.id.endsWith(':'+id));}
export function parseLol(html){const arrays=arraysForKey(html,'events');if(!arrays.length)throw Error('LoL Esports 일정 형식 변경');const found=new Map();for(const e of arrays.flat()){if(!Array.isArray(e.matchTeams)||!e.startTime)continue;const selected=e.matchTeams.filter(isFirstTeamLol);for(const t of selected){const out=event(t.code.toLowerCase(),`lol-${e.id}-${t.code}`,e.startTime,e.matchTeams.map(t=>t.code||t.name).join(' vs '),`${e.league?.name||'LoL'} · ${e.blockName||''}`,L,e.state==='completed'?'종료':e.state==='inProgress'?'진행 중':'예정');out.participants=lolParticipants(e.matchTeams);found.set(out.id,out);}}return [...found.values()];}
async function lol(month){const [y,m]=month.split('-').map(Number);const from=new Date(`${month}-01T00:00:00+09:00`).toISOString(),to=new Date(Date.UTC(y,m,1)-9*3600000).toISOString();let pageToken=null,events=[],seen=new Set();for(let page=0;page<30;page++){const body={operationName:'homeEvents',extensions:{persistedQuery:{version:1,sha256Hash:'7246add6f577cf30b304e651bf9e25fc6a41fe49aeafb0754c16b5778060fc0a'}},variables:{hl:'ko-KR',sport:['lol'],eventType:'match',pageSize:300,eventDateStart:from,eventDateEnd:to,...(pageToken?{pageToken}:{})}};const response=await fetch('https://lolesports.com/api/gql',{method:'POST',headers:{'Content-Type':'application/json','apollographql-client-name':'Matchday','apollographql-client-version':'1.0'},body:JSON.stringify(body),signal:AbortSignal.timeout(18000)});if(!response.ok)throw Error(`LoL Esports 응답 ${response.status}`);const j=await response.json();if(j.errors||!Array.isArray(j.data?.esports?.events))throw Error('LoL Esports 일정 형식 변경');const rows=j.data.esports.events;for(const e of rows){if(!e.matchTeams)continue;for(const team of e.matchTeams.filter(isFirstTeamLol)){const out=event(team.code.toLowerCase(),`lol-${e.id}-${team.code}`,e.startTime,e.matchTeams.map(t=>t.code||t.name).join(' vs '),`${e.league?.name||'LoL'} · ${e.blockName||''}`,L,e.state==='completed'?'종료':e.state==='inProgress'?'진행 중':'예정');out.participants=lolParticipants(e.matchTeams);if(e.state==='completed')out.score=e.matchTeams.map(t=>t.result?.gameWins??'?').join(' : ');if(out.date.startsWith(month))events.push(out);}}const token=j.data.esports.pages?.newer;if(!token||!rows.length)break;if(seen.has(token))throw Error('LoL 페이지 조회가 반복되었습니다');seen.add(token);pageToken=token;if(page===29)throw Error('LoL 기록 조회 한도 초과');}return {events:[...new Map(events.map(e=>[e.id,e])).values()],scope:'과거 경기·결과 및 예정 대진 · LoL Esports'};}
export function parseF1(html,url){const blocks=[...html.matchAll(/<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)];let valid=false;const result=[];for(const b of blocks){let j;try{j=JSON.parse(b[1]);}catch{continue;}for(const race of (Array.isArray(j)?j:[j])){if(!race.subEvent)continue;valid=true;for(const s of race.subEvent){if(!s.startDate||/practice/i.test(s.name))continue;let label=s.name.replace(/^Sprint Qualifying/i,'스프린트 예선').replace(/^Qualifying/i,'예선').replace(/^Sprint/i,'스프린트').replace(/^Race/i,'결승');result.push(event('f1',s['@id']||url+s.name,s.startDate,label,race.location?.name||'F1',url,/cancel/i.test(s.eventStatus||'')?'취소':Date.parse(s.endDate||s.startDate)<Date.now()?'종료':'예정'));}}}if(!valid)throw Error('F1 세션 일정 미공개 또는 형식 변경');return result;}
async function f1(month){const [year,m]=month.split('-').map(Number);const url=`https://www.formula1.com/en/racing/${year}`,html=await get(url);const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];const wanted=[months[m-1],months[(m+10)%12],months[m%12]];const urls=new Set();for(const a of html.matchAll(/<a\b[^>]*href="(\/en\/racing\/\d{4}\/[a-z0-9-]+)"[^>]*>([\s\S]*?)<\/a>/g)){const content=textOnly(a[2]);if(wanted.some(x=>new RegExp(`\\b${x}\\b`,'i').test(content))&&!/testing/i.test(a[1]))urls.add('https://www.formula1.com'+a[1]);}if(!urls.size)throw Error('F1 해당 기간 일정 미공개 또는 형식 변경');const events=(await parallelMap([...urls],3,async u=>parseF1(await get(u),u))).flat().filter(e=>e.date.startsWith(month));return {events:[...new Map(events.map(e=>[e.id,e])).values()],scope:'예선·스프린트·결승 · F1 공식'};}
export function vlrUpcomingLinks(html){if(!html.includes('Nongshim RedForce')||!html.includes('team-summary'))throw Error('VLR 팀 페이지 형식 변경');const i=html.search(/Upcoming\s+matches/i);if(i<0){if(/Recent\s+results/i.test(html))return [];throw Error('VLR 일정 확인 불가');}const end=(()=>{const offset=html.slice(i).search(/Recent\s+results/i);return offset<0?-1:i+offset;})();const section=html.slice(i,end<0?undefined:end);return [...new Set([...section.matchAll(/href="(\/\d+\/[^"?]+)"/g)].map(m=>'https://www.vlr.gg'+m[1]))].slice(0,12);}
export function vlrTimestamp(html){
 const block=html.match(/<div\b[^>]*class="match-header-date"[^>]*>([\s\S]*?)<div\b[^>]*class="match-header-vs/i)?.[1]||html.slice(html.indexOf('class="match-header-date"'),html.indexOf('class="match-header-date"')+1600);
 const stamp=block.match(/data-utc-ts="(\d{4}-\d{2}-\d{2}) [^"]+"/)?.[1];
 const day=block.match(/data-moment-format="dddd, MMMM D"[^>]*>\s*\w+,\s*(\w+)\s+(\d{1,2})/);
 const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
 const displayDate=day&&months.includes(day[1])?stamp?.slice(0,4)+'-'+String(months.indexOf(day[1])+1).padStart(2,'0')+'-'+day[2].padStart(2,'0'):stamp;
 const clock=block.match(/data-moment-format="h:mm A z"[^>]*>\s*(\d{1,2}):(\d{2})\s*(AM|PM)\s*([A-Z]+)\s*</i);
 const offsets={UTC:0,GMT:0,KST:9,JST:9,HKT:8,SGT:8,AEST:10,AEDT:11,EST:-5,EDT:-4,PST:-8,PDT:-7,CET:1,CEST:2,BST:1};
 if(!stamp||!clock||!(clock[4] in offsets))throw Error('VLR 표시 시간대 확인 실패');
 const hour=Number(clock[1])%12+(clock[3].toUpperCase()==='PM'?12:0);
 return new Date(Date.parse(displayDate+'T'+String(hour).padStart(2,'0')+':'+clock[2]+':00Z')-offsets[clock[4]]*3600000).toISOString();
}
export function parseVlrMatch(html,url){const stamp=vlrTimestamp(html);const name=textOnly(html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||'').split('|')[0].split('VLR.gg')[0].trim();if(!stamp||!name)throw Error('VLR 경기 시간 미정');const out=event('ns',url,stamp,name,'VALORANT · VLR.gg',url);out.participants=[...html.matchAll(/<a\b[^>]*class="[^"]*\bmatch-header-link\b[^"]*"[^>]*>([\s\S]*?)<\/a>/gi)].map(m=>{const tag=m[1].match(/<img\b[^>]*>/i)?.[0]||'';const src=tag.match(/\bsrc=["']([^"']+)["']/i)?.[1];const alt=tag.match(/\balt=["']([^"']+)["']/i)?.[1];const heading=m[1].match(/class=["'][^"']*\bwf-title-med\b[^"']*["'][^>]*>([\s\S]*?)<\/div>/i)?.[1];const teamName=textOnly(heading||alt||'').replace(/ team logo$/i,'');return teamName?{name:teamName,logo:safeLogo(src)}:null;}).filter(Boolean).slice(0,2);if(out.participants.length===2)out.title=out.participants.map(t=>t.name==='Nongshim RedForce'?'농심 레드포스':t.name).join(' vs ');return out;}
async function vlr(month){const urls=vlrUpcomingLinks(await get(V)).map(url=>({url})),events=[];let next='https://www.vlr.gg/team/matches/11060/nongshim-redforce/';const earliest=Date.parse(`${month}-01T00:00:00+09:00`)-86400000;for(let page=0;next;page++){if(page>=35)throw Error('VLR 과거 기록 조회 한도 초과');const html=await get(next);let oldest=Infinity;const cards=[...html.matchAll(/<a\s+href="([^"]+)"\s+class="wf-card fc-flex m-item"[^>]*>([\s\S]*?)<\/a>/g)];if(!cards.length&&!/No matches/i.test(html))throw Error('VLR 과거 경기 형식 변경');for(const [,href,card] of cards){const d=card.match(/class="m-item-date">\s*<div>\s*(\d{4}\/\d{2}\/\d{2})/)?.[1]?.replaceAll('/','-');if(!d)continue;const date=Date.parse(d+'T12:00:00Z');oldest=Math.min(oldest,date);const end=Date.parse(`${month}-28T00:00:00Z`)+5*86400000;if(date<earliest||date>end)continue;const result=card.match(/class="m-item-result[^"]*"[^>]*>([\s\S]*?)<\/div>\s*<span>(\d+)<\/span>/);const scoreText=textOnly(card.match(/class="m-item-result[^"]*"[^>]*>([\s\S]*?)<i /)?.[1]||'');const score=scoreText.match(/(\d+)\s*:\s*(\d+)/);urls.push({url:new URL(href,V).href,score:score?`${score[1]} : ${score[2]}`:null,logos:[...card.matchAll(/<div\b[^>]*class="[^"]*\bm-item-logo\b[^"]*"[^>]*>\s*<img\b[^>]*src="([^"]+)"/gi)].map(m=>safeLogo(m[1])),names:[...card.matchAll(/class="m-item-team-name">([\s\S]*?)<\/span>/g)].map(x=>textOnly(x[1]))});}if(oldest<earliest)break;const href=html.match(/<link rel="next" href="([^"]+)"/)?.[1];next=href?new URL(href,V).href:null;}const details=await parallelMap([...new Map(urls.map(x=>[x.url,x])).values()],4,async item=>applyVlrResult(parseVlrMatch(await get(item.url),item.url),item));events.push(...details.filter(e=>e.date.startsWith(month)));return {events,scope:'과거 경기·결과 및 예정 대진 · VLR.gg'};}
async function loadSchedule(source,month,origin='https://matchday.local',force=false){if(!['lotte','daegu','barca','lol','vlr','f1'].includes(source)||!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))throw Error('잘못된 일정 요청');const key=`${source}:${month}`,cache=globalThis.caches?.default,req=new Request(`${origin}/__source_cache/${source}/${month}`);let old=memory.get(key);if(!old&&cache){const r=await cache.match(req);if(r)old=await r.json();}if(!force&&old&&Date.now()-Date.parse(old.checkedAt)<5*60000)return {...old,cached:true};try{const data=await (['lotte','daegu','barca'].includes(source)?naver(source,month):source==='lol'?lol(month):source==='vlr'?vlr(month):f1(month));const fresh={...data,source,month,checkedAt:new Date().toISOString(),ok:true,stale:false};memory.set(key,fresh);if(memory.size>100)memory.delete(memory.keys().next().value);if(cache)await cache.put(req,Response.json(fresh,{headers:{'Cache-Control':'public,max-age=604800'}}));return fresh;}catch(e){return {source,month,events:old?.events||[],checkedAt:old?.checkedAt||null,ok:false,stale:!!old,error:e.message,scope:old?.scope||'일정을 가져오지 못했습니다'};}}

export function applyVlrResult(e,item){
 if(item.names?.length===2){
  const logos=new Map((e.participants||[]).map(p=>[p.name,p.logo]));
  e.participants=item.names.map((name,index)=>({name,logo:item.logos?.[index]||logos.get(name)||null}));
  e.title=item.names.map(n=>n==='Nongshim RedForce'?'농심 레드포스':n).join(' vs ');
 }
 if(item.score){e.score=item.score;e.status='종료';}
 return e;
}

export async function getSchedule(source,month,origin='https://matchday.local',force=false){const key=source+':'+month;if(pendingSchedules.has(key))return pendingSchedules.get(key);const job=loadSchedule(source,month,origin,force).finally(()=>pendingSchedules.delete(key));pendingSchedules.set(key,job);return job;}
